pimcore_data_hub:
    configurations:
        import:
            general:
                type: dataImporterDataObject
                path: null
                name: import
                modificationDate: 1659862963
                createDate: 1659862963
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
